### ISSUE TITLE
Better API documentation

### ISSUE THREAD

**Issue by newyork-anthonyng** [enkidevs/seapig#14]
Thank you for this project!

Should we update the [API section](https://github.com/enkidevs/seapig#api) to include all 4 schema constants?

The current documentation only references `OPTIONAL` and `REQUIREDS`, and makes no distinction that plural counterparts exist. 

I know that the documentation makes reference to it somewhere in the middle of the docs, but it might be confusing for new developers who jump straight to the `API` section.

**Comment by nem035** [comment]
Hey @newyork-anthonyng, thanks for the suggestion, that's a good idea, I can definitely see how that might get confusing. Do you have a particular idea on how to add it and/or did you want to make a PR for it?

**Comment by newyork-anthonyng** [comment]
@nem035 

I'd be more than happy to create a PR for this. What do you think about the below? I added in `iconsChildren`, and `labelsChildren`.

```javascript
const {
  iconChildren,
  iconsChildren,
  labelChildren,
  labelsChildren,
  imageChildren,
  rest, // array of children not matching any of the schema props
} = seapig(children, {
  icon: OPTIONAL, // use OPTIONAL to specify only one optional child prop
  icons: OPTIONALS, // use OPTIONALS to specify any amount of optional child props
  label: REQUIRED, // use REQUIRED to specify only one required child prop,
  labels: REQUIREDS, // use REQUIREDS to specify at least one required child prop,
  image: { // pass an object with `min` and/or `max`
    min: 1, // default is `0` if only `max` is specified
    max: 2  // default is `Infinity` if only `min` is specified
  }
})
```

**Comment by nem035** [comment]
This looks good to me, feel free to submit the changes whenever
