### ISSUE TITLE
React warnings for non-boolean attribute

### ISSUE THREAD

**Issue by newyork-anthonyng** [enkidevs/seapig#16]
When using `seapig` and passing on an attribute like so...

```jsx
<SomeSeapigComponent>
  <h1 foo>Hello World</h1>
</SomeSeapigComponent>
```

React throws a warning.

![screen shot 2018-01-10 at 10 10 16 am](https://user-images.githubusercontent.com/14035529/34788105-7d8a3ca2-f5ee-11e7-93b6-52c4a85faa58.png)

I believe this is because React is trying to render an actual `<h1 />` tag with an empty `foo` attribute. 

Should `seapig` remove the designated props from the component?

We could do this by using `React.createElement` to clone the child and remove the designated props. It could look something like this:
```jsx
// https://github.com/enkidevs/seapig/blob/master/src/index.js#L80
Children.toArray(children).forEach(child => {
    if (!child) {
      return;
    }

    const propName = propNames.find(p => child.props[p]) || REST;

    // clone the child and remove the designated prop from it
    const childType = child.type;
    const newProps = { ...child.props };
    delete newProps[propName];
    const newChild = createElement(childType, newProps);

    result[propName === REST ? propName : convertPropname(propName)].push(
      newChild
    );
  });
```

**Comment by nem035** [comment]
Hmmm, that's an interesting idea, the problem is that that wouldn't work when we want the attributes to have some meaning other than a seapig declaration:

```jsx
<SomeSeapigComponent>
  {/* Should we remove `primary` here?*/}
  <Button primary>Action</Button>
</SomeSeapigComponent>
```

I'm not sure this is might be outside the scope of `seapig`.

**Comment by newyork-anthonyng** [comment]
@nem035 Agreed.

I just wanted to open the issue in case others run into this warning.
