### ISSUE TITLE
rename library or add more keyswords

### ISSUE THREAD

**Issue by mrtnbroder** [enkidevs/seapig#20]
I just searched 30 minutes for exactly this library but I just couldn't find it because I was not using the right keyword. However, I expected to find this library related to the topic of `slots`, or `placeholder` or even `tunnel`, like https://github.com/dschnare/react-slot or https://www.npmjs.com/package/react-tunnel

Please add these related keywords :) !

**Comment by mrtnbroder** [comment]
Oh yeah, second result! Even better than `react-slots`, lol.
![screen shot 2018-05-17 at 16 55 12](https://user-images.githubusercontent.com/1118826/40185554-292149b2-59f3-11e8-907a-c9621dcc1da3.jpg)

**Comment by mathieudutour** [comment]
oh waow nice :)
