### ISSUE TITLE
React 15 is a hard dependency

### ISSUE THREAD

**Issue by ryanirilli** [enkidevs/seapig#23]
I see in `package.json` React was moved to a peerDependency. Can you please publish this change?

https://github.com/enkidevs/seapig/commit/4e5ff6be598b622a9901a401f71f2eb69ab9eec5

**Comment by nem035** [comment]
Hi @ryanirilli , just made a few changes, will publish in a min

**Comment by nem035** [comment]
See: https://github.com/enkidevs/seapig/pull/24

**Comment by nem035** [comment]
Solved: https://www.npmjs.com/package/seapig/v/0.4.1

**Comment by nem035** [comment]
Things are looking much better 😆 	

<img width="842" alt="screen shot 2019-03-04 at 4 38 16 pm" src="https://user-images.githubusercontent.com/9661806/53764717-09198b00-3e9c-11e9-8c50-5ae5f7a39edc.png">

**Comment by ryanirilli** [comment]
Thank you!
